import { demoCalendars } from '../demoData';
import { CalendarData, EventObj } from '../types';

const today = new Date();
const year = today.getFullYear();
const month = today.getMonth();
const date = today.getDate();

const createDate = (dayOffset: number, hours: number, minutes: number): Date => new Date(year, month, date + dayOffset, hours, minutes);

// Helper for boilerplate event data to keep the array clean
const baseEvent = {
  organizer: 'joe@example.com',
  startTimeZone: 'America/New_York', // Adjust as needed
  endTimeZone: 'America/New_York',
  eventType: 'default',
  sequence: 0,
  reminders: { useDefault: true },
};

// Calendar: joe@gmail.com (Personal / Main)
export const demoEventsJoe1: EventObj[] = [
  {
    ...baseEvent,
    id: 'pers-1',
    title: 'Grocery Shopping',
    description: 'Weekly restock.',
    location: "Trader Joe's",
    allDay: false,
    startDate: createDate(-2, 18, 30),
    endDate: createDate(-2, 19, 30),
    calendarId: 'joe@example.com',
  },
  {
    ...baseEvent,
    id: 'pers-2',
    title: 'Dinner with Sarah',
    description: 'Catch up over sushi.',
    location: 'Sakura Sushi',
    allDay: false,
    startDate: createDate(-1, 19, 0),
    endDate: createDate(-1, 20, 30),
    calendarId: 'joe@example.com',
  },
  {
    ...baseEvent,
    id: 'pers-3',
    title: 'Dentist Appointment',
    description: 'Regular cleaning.',
    location: 'Smile Dental Clinic',
    allDay: false,
    startDate: createDate(0, 16, 0), // Today
    endDate: createDate(0, 17, 0),
    calendarId: 'joe@example.com',
  },
  {
    ...baseEvent,
    id: 'pers-4',
    title: "Mom's Birthday",
    description: "Don't forget to call!",
    location: '',
    allDay: true,
    startDate: createDate(1, 0, 0), // Tomorrow
    endDate: createDate(1, 23, 59),
    calendarId: 'joe@example.com',
  },
  {
    ...baseEvent,
    id: 'pers-5',
    title: 'Pick up Dry Cleaning',
    description: 'Grab the suit for the weekend.',
    location: 'Downtown Cleaners',
    allDay: false,
    startDate: createDate(1, 17, 30),
    endDate: createDate(1, 18, 0),
    calendarId: 'joe@example.com',
  },
  {
    ...baseEvent,
    id: 'pers-6',
    title: 'Apartment Deep Clean',
    description: 'Vacuum, mop, laundry.',
    location: 'Home',
    allDay: false,
    startDate: createDate(2, 10, 0),
    endDate: createDate(2, 14, 0),
    calendarId: 'joe@example.com',
  },
];

// Calendar: Joe's Work (demo-joe-schedule-1)const today = new Date();
const WORK_CAL_ID = 'demo-joe-schedule-1@example.com';
const ORGANIZER = 'joe@example.com';
const TZ = 'America/Los_Angeles'; // Set to Pacific Time for SoCal context
export const joeWorkEvents: EventObj[] = [
  // Day -3 (Monday)
  {
    id: 'work-evt-1',
    title: 'Weekly Marketing All-Hands',
    description: 'Company wide marketing alignment.',
    location: 'Main Boardroom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-3, 9, 30),
    endDate: createDate(-3, 10, 30),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-2',
    title: 'Lunch with Jim',
    description: 'Burgers.',
    location: 'Downtown Diner',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-3, 12, 0),
    endDate: createDate(-3, 13, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-3',
    title: 'TikTok Campaign Planning',
    description: 'Drafting storyboard for SoCal fall promo.',
    location: 'Conference Room B',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-3, 14, 0),
    endDate: createDate(-3, 16, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },

  // Day -2 (Tuesday)
  {
    id: 'work-evt-4',
    title: 'Content Review',
    description: 'Reviewing video cuts from the production team.',
    location: 'Edit Bay',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-2, 10, 0),
    endDate: createDate(-2, 11, 30),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-5',
    title: 'Ad Budget Meeting',
    description: 'Reallocating spend towards higher-performing video formats.',
    location: 'Finance Office',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-2, 13, 0),
    endDate: createDate(-2, 14, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },

  // Day -1 (Wednesday)
  {
    id: 'work-evt-6',
    title: 'Client Alignment Call',
    description: 'Weekly check-in with SoCal stakeholders.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-1, 9, 0),
    endDate: createDate(-1, 10, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-7',
    title: 'Lunch with Jack',
    description: 'Catch up over tacos.',
    location: 'Local Taqueria',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-1, 12, 0),
    endDate: createDate(-1, 13, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-8',
    title: 'Asset Generation: TikTok Shorts',
    description: 'Finalizing text overlays.',
    location: 'Desk',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-1, 14, 30),
    endDate: createDate(-1, 16, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },

  // Day 0 (Thursday - Today)
  {
    id: 'work-evt-9',
    title: 'Q3 Strategy Sync',
    description: 'Aligning marketing deliverables for Q3 metrics.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 11, 0),
    endDate: createDate(0, 12, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-10',
    title: 'Lunch with Jim and Jessica',
    description: 'Team lunch outing.',
    location: 'Poke Bowl Place',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 12, 30),
    endDate: createDate(0, 13, 30),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-11',
    title: 'Marketing Team Weekly Sync',
    description: 'Status updates across all marketing verticals.',
    location: 'Main Boardroom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 16, 0),
    endDate: createDate(0, 17, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },

  // Day 1 (Friday)
  {
    id: 'work-evt-12',
    title: 'Influencer Outreach Planning',
    description: 'Scouting TikTok influencers for the upcoming brand deal.',
    location: 'Focus Room 2',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(1, 10, 30),
    endDate: createDate(1, 11, 30),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },
  {
    id: 'work-evt-13',
    title: 'Analytics Review',
    description: 'Reviewing engagement metrics from the previous TikTok campaign.',
    location: 'Desk',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(1, 14, 0),
    endDate: createDate(1, 15, 0),
    startTimeZone: TZ,
    endTimeZone: TZ,
    eventType: 'default',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: WORK_CAL_ID,
  },

  // Days 2 and 3 (Saturday and Sunday) omitted to adhere to 9-5 weekday constraint.
];

// Calendar: Gym, Joe (demo-joe-schedule-2)
export const demoEventsJoe3: EventObj[] = [
  {
    ...baseEvent,
    id: 'gym-1',
    title: 'Morning Run (5k)',
    description: 'Pace: 8:30/mi',
    location: 'Local Park',
    allDay: false,
    startDate: createDate(-2, 6, 30),
    endDate: createDate(-2, 7, 30),
    calendarId: 'demo-joe-schedule-2@example.com',
  },
  {
    ...baseEvent,
    id: 'gym-2',
    title: 'Weightlifting - Pull Day',
    description: 'Back and biceps.',
    location: 'Iron Gym',
    allDay: false,
    startDate: createDate(-1, 17, 30),
    endDate: createDate(-1, 18, 45),
    calendarId: 'demo-joe-schedule-2@example.com',
  },
  {
    ...baseEvent,
    id: 'gym-3',
    title: 'Vinyasa Yoga',
    description: 'Active recovery.',
    location: 'Zen Studio',
    allDay: false,
    startDate: createDate(0, 7, 0), // Today
    endDate: createDate(0, 8, 0),
    calendarId: 'demo-joe-schedule-2@example.com',
  },
  {
    ...baseEvent,
    id: 'gym-4',
    title: 'Weightlifting - Push Day',
    description: 'Chest, shoulders, triceps.',
    location: 'Iron Gym',
    allDay: false,
    startDate: createDate(1, 18, 0),
    endDate: createDate(1, 19, 15),
    calendarId: 'demo-joe-schedule-2@example.com',
  },
  {
    ...baseEvent,
    id: 'gym-5',
    title: 'Rest Day',
    description: 'Stretching only.',
    location: 'Home',
    allDay: true,
    startDate: createDate(2, 0, 0),
    endDate: createDate(2, 23, 59),
    calendarId: 'demo-joe-schedule-2@example.com',
  },
];

// Calendar: Meetings, Joe (demo-joe-schedule-3)
export const demoEventsJoe4: EventObj[] = [
  {
    ...baseEvent,
    id: 'meet-1',
    title: 'Daily Standup',
    description: 'Sync with the dev team.',
    location: 'Zoom',
    allDay: false,
    startDate: createDate(-2, 10, 0),
    endDate: createDate(-2, 10, 30),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
  {
    ...baseEvent,
    id: 'meet-2',
    title: '1:1 with Manager',
    description: 'Weekly check-in.',
    location: 'Google Meet',
    allDay: false,
    startDate: createDate(-1, 11, 0),
    endDate: createDate(-1, 11, 30),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
  {
    ...baseEvent,
    id: 'meet-3',
    title: 'Daily Standup',
    description: 'Sync with the dev team.',
    location: 'Zoom',
    allDay: false,
    startDate: createDate(0, 10, 0), // Today
    endDate: createDate(0, 10, 30),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
  {
    ...baseEvent,
    id: 'meet-4',
    title: 'Client Demo: Beta Release',
    description: 'Showing the new features to Acme Corp.',
    location: 'Zoom',
    allDay: false,
    startDate: createDate(0, 13, 0), // Today
    endDate: createDate(0, 14, 0),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
  {
    ...baseEvent,
    id: 'meet-5',
    title: 'Daily Standup',
    description: 'Sync with the dev team.',
    location: 'Zoom',
    allDay: false,
    startDate: createDate(1, 10, 0),
    endDate: createDate(1, 10, 30),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
  {
    ...baseEvent,
    id: 'meet-6',
    title: 'Design Handoff',
    description: 'Reviewing Figma files for next sprint.',
    location: 'Conference Room B',
    allDay: false,
    startDate: createDate(1, 14, 30),
    endDate: createDate(1, 15, 30),
    calendarId: 'demo-joe-schedule-3@example.com',
  },
];

export const demoEvents: CalendarData[] = [
  {
    id: demoCalendars[0].calendarId,
    owner: demoCalendars[0].dataOwner,
    name: demoCalendars[0].calendarName,
    color: demoCalendars[0].calendarDefaultColor,
    events: [...demoEventsJoe1],
  },
  {
    id: demoCalendars[1].calendarId,
    owner: demoCalendars[1].dataOwner,
    name: demoCalendars[1].calendarName,
    color: demoCalendars[1].calendarDefaultColor,
    events: [...joeWorkEvents],
  },
  {
    id: demoCalendars[2].calendarId,
    owner: demoCalendars[2].dataOwner,
    name: demoCalendars[2].calendarName,
    color: demoCalendars[2].calendarDefaultColor,
    events: [...demoEventsJoe3],
  },
  {
    id: demoCalendars[3].calendarId,
    owner: demoCalendars[3].dataOwner,
    name: demoCalendars[3].calendarName,
    color: demoCalendars[3].calendarDefaultColor,
    events: [...demoEventsJoe4],
  },
];
