import { EventObj } from '../types';

const CALENDAR_ID = 'demo-joe-schedule-1@example.com';
const ORGANIZER = 'joe@example.com';
const TIMEZONE = 'America/New_York';

const today = new Date();
const year = today.getFullYear();
const month = today.getMonth();
const date = today.getDate();

export const createDate = (dayOffset: number, hours: number, minutes: number): Date =>
  new Date(year, month, date + dayOffset, hours, minutes);

export const recentEvents: EventObj[] = [
  {
    id: 'evt-recent-1',
    title: 'Morning Standup',
    description: 'Daily team sync to discuss blockers and progress.',
    location: 'Zoom Room A',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 9, 30),
    endDate: createDate(0, 10, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-2',
    title: 'Focus Time: Frontend Architecture',
    description: 'Deep work on the new calendar module components.',
    location: 'Desk',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 10, 0),
    endDate: createDate(0, 12, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'focus',
    sequence: 0,
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 5 }] },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-3',
    title: 'Lunch with Sarah',
    description: 'Catching up over tacos.',
    location: 'Downtown Taqueria',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 12, 30),
    endDate: createDate(0, 13, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-4',
    title: '1:1 with Manager',
    description: 'Weekly check-in and career growth discussion.',
    location: 'Office 4B',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(0, 14, 0),
    endDate: createDate(0, 14, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-5',
    title: 'Code Review Session',
    description: 'Reviewing PRs for the mobile app release.',
    location: 'Discord Voice Channel',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-1, 11, 0),
    endDate: createDate(-1, 12, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-6',
    title: 'Dentist Appointment',
    description: 'Routine cleaning.',
    location: 'Smile Dental Clinic',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-1, 15, 0),
    endDate: createDate(-1, 16, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: false, overrides: [{ method: 'email', minutes: 1440 }] },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-7',
    title: 'Design Handoff',
    description: 'Going over the Figma files for the new dashboard.',
    location: 'Google Meet',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(1, 10, 30),
    endDate: createDate(1, 11, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-8',
    title: 'Team Retrospective',
    description: 'What went well, what can we improve?',
    location: 'Conference Room 2',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(1, 15, 0),
    endDate: createDate(1, 16, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-9',
    title: 'Company All-Hands',
    description: 'Quarterly business updates.',
    location: 'Main Auditorium / Stream',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(2, 13, 0),
    endDate: createDate(2, 14, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-10',
    title: 'Gym Workout',
    description: 'Upper body day.',
    location: 'Local Fitness Center',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-2, 17, 30),
    endDate: createDate(-2, 18, 45),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'health',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-11',
    title: 'Client Demo',
    description: 'Showcasing the beta version of the app.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(3, 11, 0),
    endDate: createDate(3, 12, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 15 }] },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-recent-12',
    title: 'Weekly Grocery Run',
    description: 'Stock up for the week.',
    location: 'Whole Foods',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(3, 18, 0),
    endDate: createDate(3, 19, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
];

export const pastEvents: EventObj[] = [
  {
    id: 'evt-past-1',
    title: 'Sprint Planning',
    description: 'Planning the previous sprint goals.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-14, 10, 0),
    endDate: createDate(-14, 11, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-2',
    title: 'HR Benefits Enrollment Q&A',
    description: 'Open enrollment info session.',
    location: 'Webinar',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-16, 13, 0),
    endDate: createDate(-16, 14, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-3',
    title: 'React Native Meetup',
    description: 'Networking and tech talks.',
    location: 'Downtown Tech Hub',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-18, 18, 30),
    endDate: createDate(-18, 21, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'networking',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-4',
    title: 'Production Deployment',
    description: 'v1.4.2 Release to App Stores.',
    location: 'Remote',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-20, 2, 0),
    endDate: createDate(-20, 4, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'devops',
    sequence: 1,
    reminders: { useDefault: false, overrides: [{ method: 'email', minutes: 60 }] },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-5',
    title: "Dad's Birthday",
    description: 'Call dad and send gift.',
    location: '',
    organizer: ORGANIZER,
    allDay: true,
    startDate: createDate(-22, 0, 0),
    endDate: createDate(-22, 23, 59),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-6',
    title: 'Performance Review',
    description: 'Mid-year check in.',
    location: "Manager's Office",
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-24, 11, 0),
    endDate: createDate(-24, 12, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-7',
    title: 'Team Offsite',
    description: 'Escape room and dinner.',
    location: 'Mystery Rooms Escapes',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-26, 14, 0),
    endDate: createDate(-26, 19, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'social',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-8',
    title: 'Car Maintenance',
    description: 'Oil change and tire rotation.',
    location: 'Jiffy Lube',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-28, 8, 0),
    endDate: createDate(-28, 9, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-9',
    title: 'Brainstorming: Q4 Features',
    description: 'Whiteboarding session for upcoming roadmap.',
    location: 'Conference Room 1',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-29, 13, 0),
    endDate: createDate(-29, 15, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-10',
    title: 'Doctor Appointment',
    description: 'Annual physical.',
    location: 'City Health Clinic',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-30, 9, 0),
    endDate: createDate(-30, 10, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'health',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-11',
    title: 'Database Migration Prep',
    description: 'Reviewing scripts before weekend maintenance.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-31, 16, 0),
    endDate: createDate(-31, 17, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-past-12',
    title: 'Weekend Hike',
    description: 'Hiking the blue trail.',
    location: 'State Park',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(-33, 7, 0),
    endDate: createDate(-33, 11, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
];

export const futureEvents: EventObj[] = [
  {
    id: 'evt-future-1',
    title: 'Next Sprint Planning',
    description: 'Setting goals for the upcoming sprint.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(14, 10, 0),
    endDate: createDate(14, 11, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-2',
    title: 'Conference Early Bird Registration Ends',
    description: 'Make sure to buy tickets for React Conf.',
    location: 'Online',
    organizer: ORGANIZER,
    allDay: true,
    startDate: createDate(16, 0, 0),
    endDate: createDate(16, 23, 59),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'reminder',
    sequence: 0,
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 1440 }] },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-3',
    title: 'Marketing Alignment',
    description: 'Syncing dev milestones with marketing announcements.',
    location: 'Conference Room 3',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(18, 14, 0),
    endDate: createDate(18, 15, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-4',
    title: 'PTO: Vacation in Mountains',
    description: 'Out of office, limited connectivity.',
    location: 'Cabin',
    organizer: ORGANIZER,
    allDay: true,
    startDate: createDate(21, 0, 0),
    endDate: createDate(25, 23, 59),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'vacation',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-5',
    title: 'Architecture Review Board',
    description: 'Presenting the new auth flow design.',
    location: 'Executive Boardroom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(26, 11, 0),
    endDate: createDate(26, 12, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-6',
    title: 'Eye Exam',
    description: 'Check up for new glasses prescription.',
    location: 'Vision Center',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(27, 9, 30),
    endDate: createDate(27, 10, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'health',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-7',
    title: 'Monthly Budget Review',
    description: 'Reviewing department expenses.',
    location: 'Zoom',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(28, 15, 0),
    endDate: createDate(28, 16, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'finance',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-8',
    title: 'Hackathon Kickoff',
    description: 'Internal company hackathon starts!',
    location: 'Cafeteria',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(30, 9, 0),
    endDate: createDate(30, 10, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'event',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-9',
    title: 'Hackathon Presentations',
    description: 'Demoing what we built in 48 hours.',
    location: 'Cafeteria',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(32, 14, 0),
    endDate: createDate(32, 16, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'event',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-10',
    title: 'Dinner with Parents',
    description: 'Monthly family dinner.',
    location: 'Olive Garden',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(34, 18, 30),
    endDate: createDate(34, 20, 30),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'personal',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-11',
    title: 'Q3 Town Hall',
    description: 'Company-wide updates from leadership.',
    location: 'Virtual',
    organizer: ORGANIZER,
    allDay: false,
    startDate: createDate(36, 11, 0),
    endDate: createDate(36, 12, 0),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'meeting',
    sequence: 0,
    reminders: { useDefault: true },
    calendarId: CALENDAR_ID,
  },
  {
    id: 'evt-future-12',
    title: 'Security Compliance Training Due',
    description: 'Mandatory annual training deadline.',
    location: 'Learning Portal',
    organizer: ORGANIZER,
    allDay: true,
    startDate: createDate(38, 0, 0),
    endDate: createDate(38, 23, 59),
    startTimeZone: TIMEZONE,
    endTimeZone: TIMEZONE,
    eventType: 'work',
    sequence: 0,
    reminders: { useDefault: false, overrides: [{ method: 'popup', minutes: 2880 }] },
    calendarId: CALENDAR_ID,
  },
];

// Combine them all if needed for your component state
export const allDemoEvents1: EventObj[] = [...pastEvents, ...recentEvents, ...futureEvents];
